version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "3003:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
